from decimal import Decimal

from django.utils.text import slugify

from rest_framework import serializers

from apps.categories.serializers import CategoryReadSerializer

from .models import Product


class ProductReadSerializer(serializers.ModelSerializer):
    """
    Read-only snapshot returned to all callers.
    Exposes category as a nested object and image as a URL string.
    """

    category = CategoryReadSerializer(read_only=True)
    image_url = serializers.SerializerMethodField()

    class Meta:
        model = Product
        fields = [
            "id",
            "name",
            "slug",
            "sku",
            "description",
            "price",
            "stock_quantity",
            "image_url",
            "category",
            "is_active",
            "created_at",
            "updated_at",
        ]
        read_only_fields = fields

    def get_image_url(self, obj: Product) -> str | None:
        if obj.image:
            request = self.context.get("request")
            if request:
                return request.build_absolute_uri(obj.image.url)
            return obj.image.url
        return None


class ProductWriteSerializer(serializers.ModelSerializer):
    """
    Admin-only write serializer.
    slug: optional — auto-generated from name on create, preserved on update.
    sku: read-only — auto-generated by the model, never accepted from the client.
    image: optional multipart upload.
    """

    slug = serializers.SlugField(required=False, allow_blank=True)
    image = serializers.ImageField(required=False, allow_null=True)
    price = serializers.DecimalField(
        max_digits=10, decimal_places=2, min_value=Decimal("0.01")
    )

    class Meta:
        model = Product
        fields = [
            "name",
            "slug",
            "description",
            "price",
            "stock_quantity",
            "image",
            "category",
            "is_active",
        ]

    def validate(self, attrs: dict) -> dict:
        if not attrs.get("slug"):
            if self.instance:
                attrs["slug"] = self.instance.slug
            else:
                attrs["slug"] = slugify(attrs.get("name", ""))
        return attrs
